load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["zsysctl_openbsd.go"],
    importmap = "k8s.io/kubernetes/vendor/k8s.io/client-go/_vendor/golang.org/x/sys/unix",
    importpath = "k8s.io/client-go/_vendor/golang.org/x/sys/unix",
    visibility = ["//visibility:public"],
)
